Use map instead of and_then
clippy emits:

  error: using `Result.and_then(|x| Ok(y))`, which is more succinctly
  expressed as `map(|x| y)`

As suggested, use `map` combinator.